### ISSUE TITLE
weak cryptographic algorithms

### ISSUE THREAD

**Issue by sy2339226** [Cyphrme/Coze#27]
Per the recommendations outlined in NIST 800-57, it is now advised to utilize algorithms with strengths of >=128 bits. We have identified within your code the use of slightly weaker 112-bit cryptographic algorithms. In an effort to bolster the security of your project, we suggest eliminating support for these 112-bit strength algorithms and transitioning to 128-bit algorithms. Implementing 128-bit algorithms will not introduce any significant additional performance overhead. Utilizing weak cryptographic algorithms could potentially lead to key leakage and certificate forgery issues.

"FuncName": "crypto/elliptic.P224",
        "SourceFilename": "github.com/Cyphrme/Coze/key.go",
	"SourceLineNum": 442, 452, 603

"FuncName": "crypto/sha256.New224",
	"SourceFilename": "github.com/Cyphrme/Coze/alg.go",
	"SourceLineNum": 459,

"FuncName": "golang.org/x/crypto/sha3.New224",
	"SourceFilename": "github.com/Cyphrme/Coze/alg.go",
	"SourceLineNum": 467,

**Comment by zamicol** [comment]
I'm assuming this is a bot?  

Yes, I'm aware of NIST's recommendations.  For now core Go Coze is going to continue to support 224.  However, there needs to be a discussion about how Go Coze handles "deprecated" or "weak" algorithms.  My thought is that eventually these should be moved to CozeX.  A discussion on what the interface should look like is needed for that to happen.
